version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@4.1.0

jobs:
  continuous-integration:
    docker:
    - image: cimg/base:stable
    resource_class: medium
    steps:
    - checkout

    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true

    - aws-cli/setup:
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        aws-region: AWS_REGION

    - aws-ecr/build-and-push-image:
        account-url: AWS_ECR_REGISTRY_ID.dkr.ecr.${AWS_REGION}.amazonaws.com
        create-repo: true
        dockerfile: Dockerfile
        path: .
        platform: linux/amd64
        push-image: true
        region: AWS_REGION
        repo: ECR_REPO
        registry-id: AWS_ECR_REGISTRY_ID
        repo-scan-on-push: true
        tag: latest,${CIRCLE_SHA1:0:7}

  continuous-deployment:
    machine: true
    resource_class: medium # Using standard resource class instead of custom
    steps:
    - checkout

    - aws-cli/setup:
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        aws-region: AWS_REGION

    - run:
        name: Login to AWS ECR
        command: |
          aws ecr get-login-password --region ${AWS_REGION} | \
          docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

    - run:
        name: Pull image from ECR
        command: |
          docker pull ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:latest

    - run:
        name: Stop and remove existing container
        command: |
          docker stop app-container || true
          docker rm app-container || true

    - run:
        name: Run Docker container with environment variables
        command: |
          docker run -d \
            --name app-container \
            -p 5000:5000 \
            -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
            -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
            -e AWS_DEFAULT_REGION="${AWS_REGION}" \
            -e MONGODB_URL="${MONGODB_URL}" \
            ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:latest

workflows:
  deploy-to-ec2:
    jobs:
    - continuous-integration:
        context: Shwa-Vehicle-Secrets
        filters:
          branches:
            only: main
    - continuous-deployment:
        context: Shwa-Vehicle-Secrets
        requires:
        - continuous-integration
        filters:
          branches:
            only: main
