version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.6.0
  aws-cli: circleci/aws-cli@5.4.1

workflows:
  build_and_deploy:
    jobs:
    - build_and_push_image
    - deploy_to_ec2:
        requires:
        - build_and_push_image

jobs:
  build_and_push_image:
    machine:
      image: ubuntu-2204:current
    steps:
    - checkout
    - aws-ecr/build_and_push_image:
        auth:
        - aws-cli/setup:
            aws_access_key_id: $AWS_ACCESS_KEY_ID
            aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
            region: $AWS_DEFAULT_REGION
        repo: $ECR_REPO
        tag: latest
        region: $AWS_DEFAULT_REGION
        account_id: $AWS_ACCOUNT_ID

  deploy_to_ec2:
    docker:
    - image: cimg/aws:2023.09
    steps:
    - checkout
    - aws-cli/setup:
        aws_access_key_id: $AWS_ACCESS_KEY_ID
        aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
        region: $AWS_DEFAULT_REGION
    - add_ssh_keys:
        fingerprints:
        - "53:9b:74:55:28:b3:32:d7:3e:3e:9b:e2:da:40:53:15"
    - run:
        name: Deploy Docker Image on EC2
        command: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP \<<EOF
            echo "Pulling latest Docker image..."
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
              docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
            docker pull "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest"
            
            echo "Stopping old container if exists..."
            docker stop myapp || true
            docker rm myapp || true
            
            echo "Running new container..."
            docker run -d --name myapp \
              -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
              -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
              -e AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
              -e MONGODB_URL="$MONGODB_URL" \
              -p 5000:5000 \
              "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest"
            echo "Deployment complete. App should be running at port 5000."
          EOF
