version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.2.0

jobs:
  continuous-integration:
    docker:
    - image: cimg/base:stable
    resource_class: medium
    steps:
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true

    - aws-ecr/build-and-push-image:
        create-repo: true
        dockerfile: Dockerfile
        path: .
        platform: linux/amd64
        push-image: true
        region: '${AWS_DEFAULT_REGION}'
        repo: dev-shwa-vehicle-ecr
        registry-id: AWS_ACCOUNT_ID
        repo-scan-on-push: true
        tag: latest

  continuous-delivery:
    machine: true
    resource_class: shwa/dev-shwa-vehicle-ecr
    steps:
    - aws-cli/setup

    - run:
        name: auth to aws ecr
        command: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 047719640457.dkr.ecr.us-east-1.amazonaws.com

    - run:
        name: pull image from private repository
        command: docker pull 047719640457.dkr.ecr.us-east-1.amazonaws.com/dev-shwa-vehicle-ecr

    - run:
        name: run image
        command: docker run -d -p 5000:5000 -e MONGODB_URL="mongodb+srv://shwa-vehicle:4ocUW5ZSxXHLJ9tE@cluster0.z7t8nq4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" 047719640457.dkr.ecr.us-east-1.amazonaws.com/dev-shwa-vehicle-ecr

workflows:
  CICD:
    jobs:
    - continuous-integration
    - continuous-delivery:
        requires:
        - continuous-integration
