version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.4
  aws-ecr: circleci/aws-ecr@9.6

executors:
  ubuntu-docker:
    docker:
    - image: cimg/base:current

jobs:
  continuous-integration:
    executor: ubuntu-docker
    steps:
    - checkout
    - aws-cli/setup # no arguments required
    - aws-ecr/login:
        region: ${AWS_DEFAULT_REGION}
    - run:
        name: Build, tag & push image
        command: |
          ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          IMAGE_TAG="latest"
          docker build -t "${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}" .
          docker push "${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
          echo "export FULL_IMAGE_URI=${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}" >> bash.env
    - persist_to_workspace:
        root: .
        paths:
        - bash.env

  continuous-deployment:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Load image URI
        command: cat bash.env >> $BASH_ENV
    - aws-cli/setup # no arguments required
    - aws-ecr/ecr-login:
        region: ${AWS_DEFAULT_REGION}
    - run:
        name: Run container on EC2
        command: |
          docker pull "${FULL_IMAGE_URI}"
          docker stop app || true
          docker rm app   || true
          docker run -d --name app \
            -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
            -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
            -e AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}" \
            -e MONGODB_URL="${MONGODB_URL}" \
            -p 5000:5000 \
            "${FULL_IMAGE_URI}"

workflows:
  deploy-app:
    jobs:
    - continuous-integration:
        context: Shwa-Vehicle-Secrets
    - continuous-deployment:
        context: Shwa-Vehicle-Secrets
        requires:
        - continuous-integration
        filters:
          branches:
            only: main
