version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.6.0
  aws-cli: circleci/aws-cli@5.4.1

jobs:
  continuous_integration:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
    - checkout
    - aws-ecr/build_and_push_image:
        auth:
        - aws-cli/setup
        repo: ECR_REPO
        tag: "latest"
        create_repo: false

  continuous_deployment:
    machine:
      image: ubuntu-2204:2024.01.1
    environment:
      ECR_REPOSITORY: $ECR_REPO
      IMAGE_TAG: latest
    steps:
    - checkout
    - aws-cli/setup
    - run:
        name: Pull and Run Application Docker Image
        command: |
          # Get login password and authenticate Docker to ECR
          echo "Logging into ECR..."
          aws ecr get-login-password --region $AWS_DEFAULT_REGION \
            | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY_URL

          # Build full image name
          FULL_IMAGE_NAME="$AWS_ECR_REGISTRY_URL/$ECR_REPOSITORY:$IMAGE_TAG"

          echo "Pulling image: $FULL_IMAGE_NAME"
          docker pull $FULL_IMAGE_NAME

          echo "Stopping and removing old container..."
          docker stop my-app-container || true
          docker rm my-app-container || true

          echo "Running new container..."
          docker run -d \
            --name my-app-container \
            -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            -e AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
            -e MONGODB_URL="$MONGODB_URL" \
            -p 5000:5000 \
            $FULL_IMAGE_NAME

workflows:
  deploy_on_push_main:
    jobs:
    - continuous_integration:
        filters:
          branches:
            only: main
    - continuous_deployment:
        requires:
        - continuous_integration
        filters:
          branches:
            only: main
