version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.7
  aws-cli: circleci/aws-cli@5.1.2

workflows:
  build_and_deploy:
    jobs:
    - build_and_push_image
    - deploy_to_ec2:
        requires:
        - build_and_push_image

jobs:
  build_and_push_image:
    machine:
      image: ubuntu-2204:current
    steps:
    - checkout
    - aws-ecr/build_and_push_image:
        auth:
        - aws-cli/setup:
            aws-access-key-id: $AWS_ACCESS_KEY_ID
            aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
            aws-region: $AWS_DEFAULT_REGION
        repo: $ECR_REPO
        tag: latest
        region: $AWS_DEFAULT_REGION
        account_id: $AWS_ACCOUNT_ID
        create_repo: true

  deploy_to_ec2:
    machine:
      resource_class: shwatech/vehicle
    steps:
    - checkout
    - run:
        name: Login to Amazon ECR
        command: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
            docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
    - run:
        name: Run Docker Image to serve users
        command: |
          docker run -d \
            -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            -e AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
            -e MONGODB_URL="$MONGODB_URL" \
            -p 5000:5000 \
            "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest"
