version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.7

jobs:
  build_and_push:
    docker:
    - image: cimg/aws:2022.06.1
    steps:
    - checkout
    - aws-ecr/build_and_push_image:
        repo: $ECR_REPO
        tag: latest
        region: $AWS_DEFAULT_REGION
        create_repo: true

  deploy_to_ec2:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
    - add_ssh_keys:
        fingerprints:
        - "<<your-ssh-key-fingerprint>>"
    - run:
        name: Deploy Docker Image on EC2 via SSH
        command: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
            docker pull $ECR_REGISTRY/$ECR_REPO:latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app \
              -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
              -e MONGODB_URL=$MONGODB_URL \
              -p 5000:5000 $ECR_REGISTRY/$ECR_REPO:latest
          "

workflows:
  build-and-deploy:
    jobs:
    - build_and_push
    - deploy_to_ec2:
        requires:
        - build_and_push
