version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@8.2

executors:
  ubuntu-docker:
    docker:
    - image: cimg/base:current

jobs:
  continuous-integration:
    executor: ubuntu-docker
    steps:
    - checkout
    - aws-cli/setup:
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        region: AWS_DEFAULT_REGION
    - aws-ecr/ecr-login:
        region: ${AWS_DEFAULT_REGION}
    - run:
        name: Build, tag & push image
        command: |
          ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          IMAGE_TAG="latest"
          docker build -t "${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}" .
          docker push "${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
          echo "export FULL_IMAGE_URI=${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}" >> bash.env
    - persist_to_workspace:
        root: .
        paths:
        - bash.env

  continuous-deployment:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Install AWS CLI v2
        command: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install
          aws --version
    - run:
        name: Log in to Amazon ECR
        command: |
          aws ecr get-login-password --region "$AWS_DEFAULT_REGION" \
          | docker login --username AWS --password-stdin \
              "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
    - run:
        name: Run container on EC2
        command: |
          source bash.env
          docker pull "${FULL_IMAGE_URI}"
          docker stop app || true
          docker rm app   || true
          docker run -d --name app \
            -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            -e AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
            -e MONGODB_URL="$MONGODB_URL" \
            -p 5000:5000 \
            "${FULL_IMAGE_URI}"

workflows:
  deploy-app:
    jobs:
    - continuous-integration:
        context: Shwa-Vehicle-Secrets
    - continuous-deployment:
        context: Shwa-Vehicle-Secrets
        requires:
        - continuous-integration
        filters:
          branches:
            only: main
