version: 2.1

executors:
  docker-executor:
    docker:
    - image: cimg/base:stable # CircleCI base Ubuntu image
    working_directory: ~/app

jobs:
  continuous-integration:
    executor: docker-executor
    steps:
    - checkout

    - run:
        name: Configure AWS CLI
        command: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config

    - run:
        name: Login to Amazon ECR
        command: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    - run:
        name: Build, tag, and push image to Amazon ECR
        command: |
          IMAGE_TAG=latest
          ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          echo "export DOCKER_IMAGE=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG" >> $BASH_ENV

  continuous-deployment:
    machine:
      image: ubuntu-2404:current
    steps:
    - checkout

    - run:
        name: Configure AWS CLI
        command: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config

    - run:
        name: Login to Amazon ECR
        command: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    - run:
        name: Run Docker container
        command: |
          docker run -d \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
            -e MONGODB_URL=$MONGODB_URL \
            -p 5000:5000 \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest

workflows:
  deploy_workflow:
    jobs:
    - continuous-integration
    - continuous-deployment:
        requires:
        - continuous-integration
