version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.1.4

workflows:
  CICD:
    jobs:
    - continuous-integration
    - continuous-delivery:
        requires:
        - continuous-integration

jobs:
  continuous-integration:
    docker:
    - image: cimg/base:stable
    resource_class: medium
    steps:
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true

    - aws-ecr/build-and-push-image:
        create-repo: true
        dockerfile: Dockerfile
        path: .
        platform: linux/amd64
        push-image: true
        region: ${AWS_DEFAULT_REGION}
        repo: ${ECR_REPO}
        registry-id: ${AWS_ACCOUNT_ID}
        repo-scan-on-push: true
        tag: latest

  continuous-delivery:
    machine: true
    resource_class: shwatech/vehicle
    steps:
    - aws-cli/setup

    - run:
        name: auth to aws ecr
        command: aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

    - run:
        name: pull image from private repository
        command: docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO}:latest

    - run:
        name: run image
        command: |
          docker run -d \
            -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            -e AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
            -e MONGODB_URL="$MONGODB_URL" \
            -p 5000:5000 \
            "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest"
